# Generated by Django 4.0 on 2024-03-16 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_image', models.ImageField(blank=True, upload_to='profileimg')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(max_length=255)),
                ('linkedin_link', models.URLField(blank=True, null=True)),
                ('locality', models.CharField(blank=True, max_length=255, null=True)),
                ('education', models.TextField(blank=True, max_length=255, null=True)),
                ('language', models.CharField(blank=True, max_length=100, null=True)),
                ('profile', models.TextField(blank=True, null=True)),
                ('experience', models.TextField(blank=True, null=True)),
                ('profession_skills', models.TextField(blank=True, null=True)),
                ('interests', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
